services:
  - type: web
    name: checkout-pix-webhook
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: WEBHOOK_URL
        value: https://checkout-pix-webhook.onrender.com/webhook-example.php
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /index.html
    plan: free
    # Configurações adicionais para garantir funcionamento
    autoDeploy: true
    branch: main
